export const campañas = [
  {
    id: "verano2024",
    nombre: "Promoción Verano 2024",
    descripcion:
      "Campaña promocional para productos de verano con descuentos especiales y ofertas limitadas para aumentar las ventas durante la temporada alta.",
    objetivo: "Aumentar ventas",
    fechaCreacion: "2024-01-10",
    fechaInicio: "2024-01-15",
    fechaFin: "2024-02-28",
    tasaApertura: "24.5%",
    tasaClics: "8.2%",
    tasaRebote: "2.1%",
    marcadosSpam: 15,
    totalDestinatarios: 1950,
    correos: [
      {
        id: "1",
        asunto: "¡Descuentos de Verano hasta 50% OFF!",
        contenido:
          "Aprovecha nuestras increíbles ofertas de verano con descuentos de hasta 50% en productos seleccionados...",
        destinatarios: "clientes@ejemplo.com",
        fecha: "2024-01-15",
        enviados: 1950,
        recibidos: 1890,
        estado: "Enviado",
        fechaEnvio: "2024-01-15",
      },
      {
        id: "2",
        asunto: "Últimos días - Ofertas de Verano",
        contenido:
          "No te pierdas las últimas oportunidades de conseguir productos de verano a precios increíbles...",
        destinatarios: "clientes@ejemplo.com",
        enviados: 1950,
        recibidos: 1875,
        fecha: "2024-01-25",
        estado: "Enviado",
        fechaEnvio: "2024-01-25",
      },
      {
        id: "3",
        asunto: "Recordatorio: Ofertas terminan mañana",
        contenido:
          "Última oportunidad para aprovechar nuestras ofertas de verano. ¡No te quedes sin tu producto favorito!",
        destinatarios: "clientes@ejemplo.com",
        enviados: 0,
        recibidos: 0,
        fecha: "2024-02-01",
        estado: "Programado",
        fechaEnvio: "2024-02-01",
      },
    ],
  },
  {
    id: "invierno2024",
    nombre: "Newsletter Mensual",
    descripcion:
      "Newsletter informativo mensual con las últimas novedades, tips y contenido de valor para mantener a nuestros clientes informados y comprometidos.",
    objetivo: "Fidelizar clientes",
    fechaCreacion: "2024-01-05",
    fechaInicio: "2024-01-10",
    fechaFin: "2024-01-31",
    tasaApertura: "18.2%",
    tasaClics: "5.8%",
    tasaRebote: "1.5%",
    marcadosSpam: 8,
    totalDestinatarios: 890,
    correos: [
      {
        id: "1",
        asunto: "Newsletter Enero - Novedades y Tips",
        contenido:
          "Descubre las últimas tendencias, consejos útiles y novedades que hemos preparado especialmente para ti...",
        destinatarios: "clientes@ejemplo.com",
        fecha: "2024-01-10",
        enviados: 890,
        recibidos: 845,
        estado: "Enviado",
        fechaEnvio: "2024-01-10",
      },
    ],
  },
  {
    id: "lanzamiento2024",
    nombre: "Lanzamiento Producto",
    descripcion:
      "Campaña de lanzamiento para nuestro nuevo producto estrella, incluyendo características, beneficios y ofertas especiales de pre-venta.",
    objetivo: "Generar leads",
    fechaCreacion: "2024-01-01",
    fechaInicio: "2024-01-08",
    fechaFin: "2024-01-22",
    tasaApertura: "31.8%",
    tasaClics: "12.4%",
    tasaRebote: "1.8%",
    marcadosSpam: 12,
    totalDestinatarios: 2100,
    correos: [
      {
        id: "1",
        asunto: "🚀 Presentamos nuestro nuevo producto",
        contenido:
          "Estamos emocionados de presentarte nuestro producto más innovador hasta la fecha...",
        destinatarios: "clientes@ejemplo.com",
        fecha: "2024-01-08",
        enviados: 2100,
        recibidos: 2050,
        estado: "Enviado",
        fechaEnvio: "2024-01-08",
      },
      {
        id: "2",
        asunto: "Oferta especial de pre-venta - Solo por tiempo limitado",
        contenido:
          "Como cliente valorado, tienes acceso exclusivo a nuestra oferta de pre-venta con descuentos especiales...",
        destinatarios: "clientes@ejemplo.com",
        fecha: "2024-01-15",
        enviados: 2100,
        recibidos: 2030,
        estado: "Enviado",
        fechaEnvio: "2024-01-15",
      },
    ],
  },
];
